services:
  test-notification-service:
    build:
      context: ../
      dockerfile: notification-service/DockerfileTest
    image: test-notification-service:1.0
    restart: always
    container_name: test-notification-service
    networks:
      - test_order_ps_network
    ports:
      - "3004:3004"

networks:
  test_order_ps_network:
    external: true
    driver: bridge
