services:
  prod-notification-service:
    build:
      context: ../
      dockerfile: notification-service/DockerfileProd
    image: prod-notification-service:1.0
    restart: always
    container_name: prod-notification-service
    networks:
      prod_order_ps_network:
        ipv4_address: 173.21.1.8
#    networks:
#      - prod_order_ps_network
    ports:
      - "4004:4004"

networks:
  prod_order_ps_network:
    external: true
    driver: bridge
