version: '3'
services:
  prod-notification-service:
    build:
      context: .
      dockerfile: DockerfileProd
    image: prod-notification-service:1.0
    restart: always
    container_name: prod-notification-service
    networks:
      - prod_order_ps_network
    ports:
      - "4004:4004"

networks:
  prod_order_ps_network:
    external: true
    driver: bridge
