services:
  dev-notification-service:
    build:
      context: ../
      dockerfile: notification-service/DockerfileDev
    image: dev-notification-service:1.0
    restart: always
    container_name: dev-notification-service
    networks:
      - dev_order_ps_network
    ports:
      - "2004:2004"

networks:
  dev_order_ps_network:
    external: true
    driver: bridge
