version: '3'
services:
  dev-config-service:
    build:
      context: .
      dockerfile: DockerfileDev
    image: dev-config-service:1.0
    restart: always
    container_name: dev-config-service
    networks:
      - dev_order_ps_network
    ports:
      - "2000:2000"

networks:
  dev_order_ps_network:
    external: true
    driver: bridge
