version: '3'
services:
  dev-order-service:
    build:
      context: .
      dockerfile: DockerfileDev
    image: dev-order-service:1.0
    restart: always
    container_name: dev-order-service
    networks:
      - dev_order_ps_network
    ports:
      - "2003:2003"

networks:
  dev_order_ps_network:
    external: true
    driver: bridge
