services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    container_name: prod-zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2114
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2114:2114"
    networks:
      test_order_ps_network:
        ipv4_address: 173.22.1.1

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    container_name: test-kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9202:9202"
      - "19202:19202"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2114'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9202,PLAINTEXT_INTERNAL://localhost:19202
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
    networks:
      test_order_ps_network:
        ipv4_address: 173.22.1.2

  mysql:
    image: mysql:latest
    restart: always
    container_name: test-order-ps-mysql
    volumes:
      #- mysql_event_booking_data:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: "test@OrderPS_2025"
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: "test@OrderPS_2025"
      MYSQL_DATABASE: 'neptune_test_store'
    command: >
      --max-connections=10000 --bind-address=0.0.0.0

    ports:
      - "8803:3306"
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1' ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      test_order_ps_network:
        ipv4_address: 173.22.1.3


networks:
  test_order_ps_network:
    external: true
    driver: bridge
#    name: test_order_ps_network
#    ipam:
#      config:
#        - subnet: 173.22.0.0/16  # Allows 173.22.0.0 to 173.21.255.255
#          ip_range: 173.22.1.0/24  # Allows 173.22.1.1 to 173.21.1.254
