server:
  port: 2001
  host: localhost
  servlet:
    contextPath: /account-service
spring:
  application:
    name: account-service
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  kafka:
    consumer:
      group-id: notification-group-id
    producer:
      bootstrap-servers: http://${server.host}:19206
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 200
      connection-timeout: 30000.0
      idle-timeout: 600000.0
      max-lifetime: 1800000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server.host}:8801/neptune_dev_store?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true
    username: 'root'
    password: 'dev@OrderPS_2025'
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
  jmx:
    default-domain: account-service

  liquibase:
    contexts: dev
    url: jdbc:mysql://${server.host}:8801/neptune_dev_store?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true
    user: 'root'
    password: 'dev@OrderPS_2025'
    change-log: classpath:/changelog/db.changelog-master.xml
    enabled: true
    dropFirst: false

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        id:
          new_generator_mappings: false
        jdbc:
          time_zone: UTC+1
        show_sql: false

app:
  jwt:
    authorities:
      key: roles
    expirationDateInMs: 86400000
    header:
      string: Authorization
    jwtCookieName: dev-order-ps
    jwtRefreshCookieName: dev-order-ps-refresh
    refreshExpiration: 8640
    refreshExpirationDateInMs: 8640
    signing:
      key: 20725b85bb97d75a04c275a18f5f1d873c4b7b4cd9b73042508082f968488f94
    token:
      prefix: Bearer
      validity: 100

#openssl rand -hex 32

management:
  metrics:
    export:
      defaults:
        enabled: false
    system:
      enabled: false