server:
  port: 2002
  host: localhost
  servlet:
    contextPath: /inventory-service
spring:
  application:
    name: inventory-service
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 200
      connection-timeout: 30000.0
      idle-timeout: 600000.0
      max-lifetime: 1800000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server.host}:3306/neptune_dev_store?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true
    username: 'root'
    password: 'david_ISAIAH_1234#$'
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
  jmx:
    default-domain: inventory-service
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        id:
          new_generator_mappings: false
        jdbc:
          time_zone: UTC+1
        show_sql: false
app:
  security:
    authentication:
      jwt:
        base64-secret: NzhiMTQ2ZGQxNjYzOTc3OWJmNzJiMDc2NmZmMzhlZTdlNDdlZjk2YWQ3NWVkZTQ2ZjM4ZGE1MDU1ODVlMDQ0ZmY1ZDEyN2VmMmM5MDQ3MjEzZmI4M2M2ZGE0MjE4ZjZkODEzZTY4YjQ3ODExODE5ZWYzMTUzZDQ2N2Q2NWVkZTg=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000