server:
  port: 2003
  host: localhost
  servlet:
    contextPath: /order-service
spring:
  application:
    name: order-service
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  kafka:
    consumer:
      group-id: notification-group-id
    producer:
      bootstrap-servers: http://${server.host}:19200
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 200
      connection-timeout: 30000.0
      idle-timeout: 600000.0
      max-lifetime: 1800000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server.host}:3306/neptune_dev_store?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true
    username: 'root'
    password: 'david_ISAIAH_1234#$'
  jmx:
    default-domain: order-service

  liquibase:
    contexts: dev
    url: jdbc:mysql://${server.host}:3306/neptune_dev_store?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true
    user: 'root'
    password: 'david_ISAIAH_1234#$'
    change-log: classpath:/changelog/db.changelog-master.xml
    enabled: true
    dropFirst: false
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        id:
          new_generator_mappings: false
        jdbc:
          time_zone: UTC+1
        show_sql: false
