server:
  port: 4001
  servlet:
    contextPath: /account-service
spring:
  application:
    name: account-service
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000.0
      idleTimeout: 600000.0
      maxLifetime: 1800000
      maximumPoolSize: 200
    url: jdbc:mysql://localhost:3331/neptune_prod_store?allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true
    username: root
    password: password
  jmx:
    default-domain: account-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        id:
          new_generator_mappings: false
        jdbc:
          time_zone: UTC+1
        show_sql: false
