version: '3'
services:
  prod-inventory-service:
    build:
      context: .
      dockerfile: DockerfileProd
    image: prod-inventory-service:1.0
    restart: always
    container_name: prod-inventory-service
    networks:
      - prod_order_ps_network
    ports:
      - "4002:4002"

networks:
  prod_order_ps_network:
    external: true
    driver: bridge
