services:
  prod-inventory-service:
    build:
      context: ../
      dockerfile: inventory-service/DockerfileProd
    image: prod-inventory-service:1.0
    restart: always
    container_name: prod-inventory-service
    networks:
      prod_order_ps_network:
        ipv4_address: 173.21.1.7
#    networks:
#      - prod_order_ps_network
    ports:
      - "4002:4002"

networks:
  prod_order_ps_network:
    external: true
    driver: bridge
