services:
  dev-inventory-service:
    build:
      context: ../
      dockerfile: inventory-service/DockerfileDev
    image: dev-inventory-service:1.0
    restart: always
    container_name: dev-inventory-service
    networks:
      - dev_order_ps_network
    ports:
      - "2002:2002"

networks:
  dev_order_ps_network:
    external: true
    driver: bridge
